// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkujmszvpiuglxzmsthv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rdWptc3p2cGl1Z2x4em1zdGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDI5MDUsImV4cCI6MjA2ODc3ODkwNX0.v8YLB46TH3SBbQLCXOP_95DDXG0daUjxktRdqEhEAGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});